# Generated by Django 4.1.7 on 2023-04-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
