# Generated by Django 4.1.7 on 2023-04-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
