# Generated by Django 4.1.7 on 2023-04-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_purchaseorder_ordercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
